apiVersion: v1
kind: ConfigMap
metadata:
  name: pioneer-hq
  labels:
    app.kubernetes.io/name: pioneer-hq
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: pioneer-hq
data:
  PIONEER_HQ_DB_PATH: /data/pioneer-hq.db
  PIONEER_HQ_DATA_DIR: /data
  PIONEER_HQ_ASSETS_DIR: /assets
