apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pioneer-hq-data
  labels:
    app.kubernetes.io/name: pioneer-hq
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: pioneer-hq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pioneer-hq-assets
  labels:
    app.kubernetes.io/name: pioneer-hq
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: pioneer-hq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
