apiVersion: v1
kind: Service
metadata:
  name: pioneer-hq
  labels:
    app.kubernetes.io/name: pioneer-hq
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: pioneer-hq
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pioneer-hq
  ports:
    - port: 8081
      targetPort: http
      name: http
