// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlite

import (
	"time"

	"api/internal/auth"
	"api/internal/session"
)

type AuthPassword struct {
	ID        int64
	Hash      string
	UpdatedAt time.Time
}

type AuthToken struct {
	TokenHash auth.TokenHash
	CreatedAt time.Time
	LastUsed  time.Time
	ExpiresAt time.Time
	ClientIp  string
}

type HistoryPoint struct {
	SessionID  session.ID
	DataType   string
	GameTimeID int64
	Data       string
}

type Instance struct {
	ID                 int64
	InitializedAt      *time.Time
	AuthMode           string
	BootstrapTokenHash *string
	CreatedAt          time.Time
}

type PlannerCatalog struct {
	SessionID string
	Catalog   string
}

type PlannerDependency struct {
	DiagramID string
	TargetID  string
	SessionID string
}

type PlannerDiagram struct {
	ID        string
	SessionID string
	Revision  int64
	Document  string
	UpdatedAt string
}

type Session struct {
	ID        session.ID
	Name      string
	Address   string
	SaveName  string
	IsPaused  int64
	CreatedAt time.Time
}

type Setting struct {
	Key   string
	Value string
}
