// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: planner.sql

package sqlite

import (
	"context"
)

const deletePlannerDependencies = `-- name: DeletePlannerDependencies :exec
DELETE FROM planner_dependencies WHERE diagram_id = ?
`

func (q *Queries) DeletePlannerDependencies(ctx context.Context, diagramID string) error {
	_, err := q.db.ExecContext(ctx, deletePlannerDependencies, diagramID)
	return err
}

const deletePlannerDiagram = `-- name: DeletePlannerDiagram :execrows
DELETE FROM planner_diagrams WHERE id = ?1 AND session_id = ?2
AND revision = ?3
`

type DeletePlannerDiagramParams struct {
	ID        string
	SessionID string
	Revision  int64
}

func (q *Queries) DeletePlannerDiagram(ctx context.Context, arg DeletePlannerDiagramParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePlannerDiagram, arg.ID, arg.SessionID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPlannerCatalog = `-- name: GetPlannerCatalog :one
SELECT catalog FROM planner_catalogs WHERE session_id = ?
`

func (q *Queries) GetPlannerCatalog(ctx context.Context, sessionID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPlannerCatalog, sessionID)
	var catalog string
	err := row.Scan(&catalog)
	return catalog, err
}

const getPlannerConsumers = `-- name: GetPlannerConsumers :many
SELECT diagram_id FROM planner_dependencies WHERE target_id = ? ORDER BY diagram_id
`

func (q *Queries) GetPlannerConsumers(ctx context.Context, targetID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPlannerConsumers, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var diagram_id string
		if err := rows.Scan(&diagram_id); err != nil {
			return nil, err
		}
		items = append(items, diagram_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPlannerDependency = `-- name: InsertPlannerDependency :exec
INSERT INTO planner_dependencies(diagram_id, target_id, session_id) VALUES (?, ?, ?)
`

type InsertPlannerDependencyParams struct {
	DiagramID string
	TargetID  string
	SessionID string
}

func (q *Queries) InsertPlannerDependency(ctx context.Context, arg InsertPlannerDependencyParams) error {
	_, err := q.db.ExecContext(ctx, insertPlannerDependency, arg.DiagramID, arg.TargetID, arg.SessionID)
	return err
}

const insertPlannerDiagram = `-- name: InsertPlannerDiagram :exec
INSERT INTO planner_diagrams(id, session_id, document) VALUES (?, ?, ?)
`

type InsertPlannerDiagramParams struct {
	ID        string
	SessionID string
	Document  string
}

func (q *Queries) InsertPlannerDiagram(ctx context.Context, arg InsertPlannerDiagramParams) error {
	_, err := q.db.ExecContext(ctx, insertPlannerDiagram, arg.ID, arg.SessionID, arg.Document)
	return err
}

const listPlannerDiagrams = `-- name: ListPlannerDiagrams :many
SELECT id, session_id, revision, document, updated_at FROM planner_diagrams
WHERE session_id = ?1 ORDER BY id
`

func (q *Queries) ListPlannerDiagrams(ctx context.Context, sessionID string) ([]PlannerDiagram, error) {
	rows, err := q.db.QueryContext(ctx, listPlannerDiagrams, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannerDiagram
	for rows.Next() {
		var i PlannerDiagram
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Revision,
			&i.Document,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePlannerCatalog = `-- name: SavePlannerCatalog :exec
INSERT INTO planner_catalogs(session_id, catalog) VALUES (?, ?)
ON CONFLICT(session_id) DO UPDATE SET catalog = excluded.catalog
`

type SavePlannerCatalogParams struct {
	SessionID string
	Catalog   string
}

func (q *Queries) SavePlannerCatalog(ctx context.Context, arg SavePlannerCatalogParams) error {
	_, err := q.db.ExecContext(ctx, savePlannerCatalog, arg.SessionID, arg.Catalog)
	return err
}

const updatePlannerDiagram = `-- name: UpdatePlannerDiagram :execrows
UPDATE planner_diagrams SET document = ?1, revision = revision + 1,
updated_at = CURRENT_TIMESTAMP
WHERE id = ?2 AND session_id = ?3 AND revision = ?4
`

type UpdatePlannerDiagramParams struct {
	Document  string
	ID        string
	SessionID string
	Revision  int64
}

func (q *Queries) UpdatePlannerDiagram(ctx context.Context, arg UpdatePlannerDiagramParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePlannerDiagram,
		arg.Document,
		arg.ID,
		arg.SessionID,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
