// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

// AuthStatus is the only unguarded query, so it is the single source of truth for
// what the client should show before it can read anything else.
type AuthStatus struct {
	// False until first-run setup completes. The client must route to setup.
	Initialized bool `json:"initialized"`
	// False on an open instance, where no access key is needed.
	AuthRequired bool `json:"authRequired"`
	// Whether this caller may read guarded fields. Always true on an open instance.
	Authenticated bool `json:"authenticated"`
}

type Belt struct {
	ID             string      `json:"id"`
	Name           string      `json:"name"`
	Location0      *Location   `json:"location0"`
	Location1      *Location   `json:"location1"`
	Connected0     bool        `json:"connected0"`
	Connected1     bool        `json:"connected1"`
	SplineData     []*Location `json:"splineData"`
	Length         float64     `json:"length"`
	ItemsPerMinute float64     `json:"itemsPerMinute"`
}

type BoundingBox struct {
	Min *Location `json:"min"`
	Max *Location `json:"max"`
}

type Cable struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	Location0  *Location `json:"location0"`
	Location1  *Location `json:"location1"`
	Connected0 bool      `json:"connected0"`
	Connected1 bool      `json:"connected1"`
	Length     float64   `json:"length"`
}

type ChangePasswordInput struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

type ChangePasswordResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Circuit struct {
	ID            string              `json:"id"`
	FuseTriggered bool                `json:"fuseTriggered"`
	Consumption   *CircuitConsumption `json:"consumption"`
	Production    *CircuitProduction  `json:"production"`
	Capacity      *CircuitCapacity    `json:"capacity"`
	Battery       *CircuitBattery     `json:"battery"`
}

type CircuitBattery struct {
	Percentage   float64 `json:"percentage"`
	Capacity     float64 `json:"capacity"`
	Differential float64 `json:"differential"`
	UntilFull    float64 `json:"untilFull"`
	UntilEmpty   float64 `json:"untilEmpty"`
}

type CircuitCapacity struct {
	Total float64 `json:"total"`
}

type CircuitConsumption struct {
	Total float64 `json:"total"`
	Max   float64 `json:"max"`
}

type CircuitProduction struct {
	Total float64 `json:"total"`
}

type CircuitsHistoryPoint struct {
	GameTimeID int        `json:"gameTimeId"`
	Circuits   []*Circuit `json:"circuits"`
}

// CompleteSetupInput claims an unset-up instance. Omitting password leaves the
// instance open, requiring no access key.
type CompleteSetupInput struct {
	SetupToken string                     `json:"setupToken"`
	Password   graphql.Omittable[*string] `json:"password,omitempty"`
}

type ConnectivityStatus struct {
	ConnectionState ConnectionState    `json:"connectionState"`
	Stage           SessionStage       `json:"stage"`
	Reason          ConnectivityReason `json:"reason"`
	// The save the server has loaded instead. Non-null exactly when connectionState is SAVE_MISMATCH.
	MismatchedSaveName *string `json:"mismatchedSaveName,omitempty"`
}

type CreateSessionInput struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	// The save the client saw when it probed the address. The server re-probes and
	// rejects the mutation if the server has since loaded a different save, so a
	// session can never be pinned to a save nobody confirmed.
	ExpectedSaveName string `json:"expectedSaveName"`
}

type DisableAuthInput struct {
	CurrentPassword string `json:"currentPassword"`
}

// DiscoveredSession is an FRM server found by sweeping the network. info is the
// same probe result the add-session form shows, so choosing one needs no second
// round trip.
type DiscoveredSession struct {
	Address string       `json:"address"`
	Info    *SessionInfo `json:"info"`
	// True when a session already exists for this server, so the client can show it without offering it.
	AlreadyAdded bool `json:"alreadyAdded"`
}

type Drone struct {
	Name           string        `json:"name"`
	Speed          float64       `json:"speed"`
	Status         DroneStatus   `json:"status"`
	Home           *DroneStation `json:"home"`
	Paired         *DroneStation `json:"paired,omitempty"`
	Destination    *DroneStation `json:"destination,omitempty"`
	X              float64       `json:"x"`
	Y              float64       `json:"y"`
	Z              float64       `json:"z"`
	Rotation       float64       `json:"rotation"`
	CircuitID      int           `json:"circuitId"`
	CircuitGroupID int           `json:"circuitGroupId"`
}

type DroneStation struct {
	Name            string       `json:"name"`
	Fuel            *Fuel        `json:"fuel,omitempty"`
	BoundingBox     *BoundingBox `json:"boundingBox"`
	IncomingRate    float64      `json:"incomingRate"`
	OutgoingRate    float64      `json:"outgoingRate"`
	InputInventory  []*ItemStats `json:"inputInventory"`
	OutputInventory []*ItemStats `json:"outputInventory"`
	X               float64      `json:"x"`
	Y               float64      `json:"y"`
	Z               float64      `json:"z"`
	Rotation        float64      `json:"rotation"`
	CircuitID       int          `json:"circuitId"`
	CircuitGroupID  *int         `json:"circuitGroupId,omitempty"`
}

type EnableAuthInput struct {
	Password string `json:"password"`
}

type Explorer struct {
	ID             string         `json:"id"`
	Name           string         `json:"name"`
	Speed          float64        `json:"speed"`
	Status         ExplorerStatus `json:"status"`
	Fuel           *Fuel          `json:"fuel,omitempty"`
	Inventory      []*ItemStats   `json:"inventory"`
	X              float64        `json:"x"`
	Y              float64        `json:"y"`
	Z              float64        `json:"z"`
	Rotation       float64        `json:"rotation"`
	CircuitID      int            `json:"circuitId"`
	CircuitGroupID *int           `json:"circuitGroupId,omitempty"`
}

type FactoryStats struct {
	TotalMachines int                `json:"totalMachines"`
	Efficiency    *MachineEfficiency `json:"efficiency"`
}

type FactoryStatsHistoryPoint struct {
	GameTimeID   int           `json:"gameTimeId"`
	FactoryStats *FactoryStats `json:"factoryStats"`
}

type Fuel struct {
	Name   string  `json:"name"`
	Amount float64 `json:"amount"`
}

type GeneratorStats struct {
	Sources []*PowerSourceEntry `json:"sources"`
}

type GeneratorStatsHistoryPoint struct {
	GameTimeID     int             `json:"gameTimeId"`
	GeneratorStats *GeneratorStats `json:"generatorStats"`
}

type Hub struct {
	ID                 string        `json:"id"`
	Name               string        `json:"name"`
	HasActiveMilestone bool          `json:"hasActiveMilestone"`
	ActiveMilestone    *HubMilestone `json:"activeMilestone,omitempty"`
	ShipDocked         bool          `json:"shipDocked"`
	ShipReturnTime     *int          `json:"shipReturnTime,omitempty"`
	BoundingBox        *BoundingBox  `json:"boundingBox"`
	X                  float64       `json:"x"`
	Y                  float64       `json:"y"`
	Z                  float64       `json:"z"`
	Rotation           float64       `json:"rotation"`
}

type HubMilestone struct {
	Name     string              `json:"name"`
	TechTier int                 `json:"techTier"`
	Type     string              `json:"type"`
	Cost     []*HubMilestoneCost `json:"cost"`
}

type HubMilestoneCost struct {
	Name          string  `json:"name"`
	Amount        float64 `json:"amount"`
	RemainingCost float64 `json:"remainingCost"`
	TotalCost     float64 `json:"totalCost"`
}

type Hypertube struct {
	ID          string       `json:"id"`
	Location0   *Location    `json:"location0"`
	Location1   *Location    `json:"location1"`
	SplineData  []*Location  `json:"splineData"`
	BoundingBox *BoundingBox `json:"boundingBox"`
}

type HypertubeEntrance struct {
	ID          string       `json:"id"`
	X           float64      `json:"x"`
	Y           float64      `json:"y"`
	Z           float64      `json:"z"`
	Rotation    float64      `json:"rotation"`
	BoundingBox *BoundingBox `json:"boundingBox"`
	PowerInfo   *PowerInfo   `json:"powerInfo"`
}

type ItemProdStats struct {
	Name                string  `json:"name"`
	Count               float64 `json:"count"`
	ProducedPerMinute   float64 `json:"producedPerMinute"`
	MaxProducePerMinute float64 `json:"maxProducePerMinute"`
	ProduceEfficiency   float64 `json:"produceEfficiency"`
	ConsumedPerMinute   float64 `json:"consumedPerMinute"`
	MaxConsumePerMinute float64 `json:"maxConsumePerMinute"`
	ConsumeEfficiency   float64 `json:"consumeEfficiency"`
	CloudCount          float64 `json:"cloudCount"`
	Minable             bool    `json:"minable"`
}

type ItemStats struct {
	Name  string  `json:"name"`
	Count float64 `json:"count"`
}

type Location struct {
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Z        float64 `json:"z"`
	Rotation float64 `json:"rotation"`
}

type LoginInput struct {
	Password string `json:"password"`
}

type LoginResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type LogoutResult struct {
	Success bool `json:"success"`
}

type Machine struct {
	Type           MachineType         `json:"type"`
	Status         MachineStatus       `json:"status"`
	Category       MachineCategory     `json:"category"`
	Productivity   float64             `json:"productivity"`
	Input          []*MachineProdStats `json:"input"`
	Output         []*MachineProdStats `json:"output"`
	BoundingBox    *BoundingBox        `json:"boundingBox"`
	X              float64             `json:"x"`
	Y              float64             `json:"y"`
	Z              float64             `json:"z"`
	Rotation       float64             `json:"rotation"`
	CircuitID      int                 `json:"circuitId"`
	CircuitGroupID *int                `json:"circuitGroupId,omitempty"`
}

type MachineEfficiency struct {
	MachinesOperating    int `json:"machinesOperating"`
	MachinesIdle         int `json:"machinesIdle"`
	MachinesPaused       int `json:"machinesPaused"`
	MachinesUnconfigured int `json:"machinesUnconfigured"`
	MachinesUnknown      int `json:"machinesUnknown"`
}

type MachineProdStats struct {
	Name       string  `json:"name"`
	Stored     float64 `json:"stored"`
	Current    float64 `json:"current"`
	Max        float64 `json:"max"`
	Efficiency float64 `json:"efficiency"`
}

type Mutation struct {
}

type Pipe struct {
	ID             string      `json:"id"`
	Name           string      `json:"name"`
	Location0      *Location   `json:"location0"`
	Location1      *Location   `json:"location1"`
	Connected0     bool        `json:"connected0"`
	Connected1     bool        `json:"connected1"`
	SplineData     []*Location `json:"splineData"`
	Length         float64     `json:"length"`
	ItemsPerMinute float64     `json:"itemsPerMinute"`
}

type PipeJunction struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Z        float64 `json:"z"`
	Rotation float64 `json:"rotation"`
}

type PlannerImportPreview struct {
	Name         string `json:"name"`
	DiagramCount int    `json:"diagramCount"`
	NodeCount    int    `json:"nodeCount"`
}

type Player struct {
	ID       string       `json:"id"`
	Name     string       `json:"name"`
	Health   float64      `json:"health"`
	Items    []*ItemStats `json:"items"`
	X        float64      `json:"x"`
	Y        float64      `json:"y"`
	Z        float64      `json:"z"`
	Rotation float64      `json:"rotation"`
}

type PowerInfo struct {
	CircuitID        int     `json:"circuitId"`
	CircuitGroupID   int     `json:"circuitGroupId"`
	PowerConsumed    float64 `json:"powerConsumed"`
	MaxPowerConsumed float64 `json:"maxPowerConsumed"`
}

type PowerSource struct {
	Count           int     `json:"count"`
	TotalProduction float64 `json:"totalProduction"`
}

type PowerSourceEntry struct {
	Type   PowerType    `json:"type"`
	Source *PowerSource `json:"source"`
}

type ProdStats struct {
	MinableProducedPerMinute float64          `json:"minableProducedPerMinute"`
	MinableConsumedPerMinute float64          `json:"minableConsumedPerMinute"`
	ItemsProducedPerMinute   float64          `json:"itemsProducedPerMinute"`
	ItemsConsumedPerMinute   float64          `json:"itemsConsumedPerMinute"`
	Items                    []*ItemProdStats `json:"items"`
}

type ProdStatsHistoryPoint struct {
	GameTimeID int        `json:"gameTimeId"`
	ProdStats  *ProdStats `json:"prodStats"`
}

type Query struct {
}

type RadarTower struct {
	ID           string           `json:"id"`
	RevealRadius float64          `json:"revealRadius"`
	Nodes        []*ResourceNode  `json:"nodes"`
	Fauna        []*ScannedFauna  `json:"fauna"`
	Flora        []*ScannedFlora  `json:"flora"`
	Signal       []*ScannedSignal `json:"signal"`
	BoundingBox  *BoundingBox     `json:"boundingBox"`
	X            float64          `json:"x"`
	Y            float64          `json:"y"`
	Z            float64          `json:"z"`
	Rotation     float64          `json:"rotation"`
}

type ResourceNode struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	ClassName    string             `json:"className"`
	Purity       ResourceNodePurity `json:"purity"`
	ResourceForm string             `json:"resourceForm"`
	ResourceType ResourceType       `json:"resourceType"`
	NodeType     NodeType           `json:"nodeType"`
	Exploited    bool               `json:"exploited"`
	X            float64            `json:"x"`
	Y            float64            `json:"y"`
	Z            float64            `json:"z"`
	Rotation     float64            `json:"rotation"`
}

type SatisfactoryAPIStatus struct {
	Running bool `json:"running"`
	PingMs  int  `json:"pingMs"`
}

type ScannedFauna struct {
	Name      FaunaType `json:"name"`
	ClassName string    `json:"className"`
	Amount    int       `json:"amount"`
}

type ScannedFlora struct {
	Name      FloraType `json:"name"`
	ClassName string    `json:"className"`
	Amount    int       `json:"amount"`
}

type ScannedSignal struct {
	Name      SignalType `json:"name"`
	ClassName string     `json:"className"`
	Amount    int        `json:"amount"`
}

type Schematic struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Tier        int              `json:"tier"`
	Type        string           `json:"type"`
	Purchased   bool             `json:"purchased"`
	Locked      bool             `json:"locked"`
	LockedPhase bool             `json:"lockedPhase"`
	Cost        []*SchematicCost `json:"cost"`
}

type SchematicCost struct {
	Name      string  `json:"name"`
	Amount    float64 `json:"amount"`
	TotalCost float64 `json:"totalCost"`
}

type Session struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
	// The save this session is pinned to, fixed when the session is created.
	SaveName        string             `json:"saveName"`
	IsPaused        bool               `json:"isPaused"`
	CreatedAt       time.Time          `json:"createdAt"`
	ConnectionState ConnectionState    `json:"connectionState"`
	Stage           SessionStage       `json:"stage"`
	OfflineReason   ConnectivityReason `json:"offlineReason"`
	// The save the server has loaded instead. Non-null exactly when connectionState is SAVE_MISMATCH.
	MismatchedSaveName *string `json:"mismatchedSaveName,omitempty"`
}

type SessionInfo struct {
	SaveName                   string  `json:"saveName"`
	IsPaused                   bool    `json:"isPaused"`
	DayLength                  int     `json:"dayLength"`
	NightLength                int     `json:"nightLength"`
	PassedDays                 int     `json:"passedDays"`
	NumberOfDaysSinceLastDeath int     `json:"numberOfDaysSinceLastDeath"`
	Hours                      int     `json:"hours"`
	Minutes                    int     `json:"minutes"`
	Seconds                    float64 `json:"seconds"`
	IsDay                      bool    `json:"isDay"`
	TotalPlayDuration          int     `json:"totalPlayDuration"`
	TotalPlayDurationText      string  `json:"totalPlayDurationText"`
}

type Settings struct {
	LogLevel LogLevel `json:"logLevel"`
}

type SetupResult struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type SinkStats struct {
	TotalPoints        float64 `json:"totalPoints"`
	Coupons            int     `json:"coupons"`
	NextCouponProgress float64 `json:"nextCouponProgress"`
	PointsPerMinute    float64 `json:"pointsPerMinute"`
}

type SinkStatsHistoryPoint struct {
	GameTimeID int        `json:"gameTimeId"`
	SinkStats  *SinkStats `json:"sinkStats"`
}

type SpaceElevator struct {
	ID            string                         `json:"id"`
	Name          string                         `json:"name"`
	BoundingBox   *BoundingBox                   `json:"boundingBox"`
	CurrentPhase  []*SpaceElevatorPhaseObjective `json:"currentPhase"`
	FullyUpgraded bool                           `json:"fullyUpgraded"`
	UpgradeReady  bool                           `json:"upgradeReady"`
	X             float64                        `json:"x"`
	Y             float64                        `json:"y"`
	Z             float64                        `json:"z"`
	Rotation      float64                        `json:"rotation"`
}

type SpaceElevatorPhaseObjective struct {
	Name      string  `json:"name"`
	Amount    float64 `json:"amount"`
	TotalCost float64 `json:"totalCost"`
}

type SplitterMerger struct {
	ID          string             `json:"id"`
	Type        SplitterMergerType `json:"type"`
	X           float64            `json:"x"`
	Y           float64            `json:"y"`
	Z           float64            `json:"z"`
	Rotation    float64            `json:"rotation"`
	BoundingBox *BoundingBox       `json:"boundingBox"`
}

type Storage struct {
	ID          string       `json:"id"`
	Type        StorageType  `json:"type"`
	Inventory   []*ItemStats `json:"inventory"`
	BoundingBox *BoundingBox `json:"boundingBox"`
	X           float64      `json:"x"`
	Y           float64      `json:"y"`
	Z           float64      `json:"z"`
	Rotation    float64      `json:"rotation"`
}

type Subscription struct {
}

type Tractor struct {
	ID             string        `json:"id"`
	Name           string        `json:"name"`
	Speed          float64       `json:"speed"`
	Status         TractorStatus `json:"status"`
	Fuel           *Fuel         `json:"fuel,omitempty"`
	Inventory      []*ItemStats  `json:"inventory"`
	X              float64       `json:"x"`
	Y              float64       `json:"y"`
	Z              float64       `json:"z"`
	Rotation       float64       `json:"rotation"`
	CircuitID      int           `json:"circuitId"`
	CircuitGroupID *int          `json:"circuitGroupId,omitempty"`
}

type Train struct {
	ID               string                 `json:"id"`
	Name             string                 `json:"name"`
	Speed            float64                `json:"speed"`
	Status           TrainStatus            `json:"status"`
	PowerConsumption float64                `json:"powerConsumption"`
	Vehicles         []*TrainVehicle        `json:"vehicles"`
	Timetable        []*TrainTimetableEntry `json:"timetable"`
	TimetableIndex   int                    `json:"timetableIndex"`
	X                float64                `json:"x"`
	Y                float64                `json:"y"`
	Z                float64                `json:"z"`
	Rotation         float64                `json:"rotation"`
	CircuitID        int                    `json:"circuitId"`
	CircuitGroupID   *int                   `json:"circuitGroupId,omitempty"`
}

type TrainRail struct {
	ID         string        `json:"id"`
	Type       TrainRailType `json:"type"`
	Location0  *Location     `json:"location0"`
	Location1  *Location     `json:"location1"`
	Connected0 bool          `json:"connected0"`
	Connected1 bool          `json:"connected1"`
	SplineData []*Location   `json:"splineData"`
	Length     float64       `json:"length"`
}

type TrainStation struct {
	Name           string                  `json:"name"`
	BoundingBox    *BoundingBox            `json:"boundingBox"`
	Platforms      []*TrainStationPlatform `json:"platforms"`
	X              float64                 `json:"x"`
	Y              float64                 `json:"y"`
	Z              float64                 `json:"z"`
	Rotation       float64                 `json:"rotation"`
	CircuitID      int                     `json:"circuitId"`
	CircuitGroupID *int                    `json:"circuitGroupId,omitempty"`
}

type TrainStationPlatform struct {
	ID           string                     `json:"id"`
	Type         TrainStationPlatformType   `json:"type"`
	Mode         TrainStationPlatformMode   `json:"mode"`
	Status       TrainStationPlatformStatus `json:"status"`
	BoundingBox  *BoundingBox               `json:"boundingBox"`
	Inventory    []*ItemStats               `json:"inventory"`
	TransferRate float64                    `json:"transferRate"`
	InflowRate   float64                    `json:"inflowRate"`
	OutflowRate  float64                    `json:"outflowRate"`
	X            float64                    `json:"x"`
	Y            float64                    `json:"y"`
	Z            float64                    `json:"z"`
	Rotation     float64                    `json:"rotation"`
}

type TrainTimetableEntry struct {
	Station string `json:"station"`
}

type TrainVehicle struct {
	Type      TrainType    `json:"type"`
	Capacity  float64      `json:"capacity"`
	Inventory []*ItemStats `json:"inventory"`
}

type Truck struct {
	ID             string       `json:"id"`
	Name           string       `json:"name"`
	Speed          float64      `json:"speed"`
	Status         TruckStatus  `json:"status"`
	Fuel           *Fuel        `json:"fuel,omitempty"`
	Inventory      []*ItemStats `json:"inventory"`
	X              float64      `json:"x"`
	Y              float64      `json:"y"`
	Z              float64      `json:"z"`
	Rotation       float64      `json:"rotation"`
	CircuitID      int          `json:"circuitId"`
	CircuitGroupID *int         `json:"circuitGroupId,omitempty"`
}

type TruckStation struct {
	Name            string       `json:"name"`
	BoundingBox     *BoundingBox `json:"boundingBox"`
	TransferRate    float64      `json:"transferRate"`
	MaxTransferRate float64      `json:"maxTransferRate"`
	Inventory       []*ItemStats `json:"inventory"`
	X               float64      `json:"x"`
	Y               float64      `json:"y"`
	Z               float64      `json:"z"`
	Rotation        float64      `json:"rotation"`
	CircuitID       int          `json:"circuitId"`
	CircuitGroupID  *int         `json:"circuitGroupId,omitempty"`
}

type UpdateSessionInput struct {
	Name     graphql.Omittable[*string] `json:"name,omitempty"`
	IsPaused graphql.Omittable[*bool]   `json:"isPaused,omitempty"`
	Address  graphql.Omittable[*string] `json:"address,omitempty"`
}

type UpdateSettingsInput struct {
	LogLevel LogLevel `json:"logLevel"`
}

type VehiclePath struct {
	Name        string          `json:"name"`
	VehicleType VehiclePathType `json:"vehicleType"`
	PathLength  float64         `json:"pathLength"`
	Vertices    []*Location     `json:"vertices"`
}

// ConnectionState is the authoritative connection state for a session, so clients
// never derive one from a pair of booleans.
type ConnectionState string

const (
	// A poller is running but FRM has not answered yet.
	ConnectionStateConnecting ConnectionState = "CONNECTING"
	// FRM answered.
	ConnectionStateOnline ConnectionState = "ONLINE"
	// FRM could not be reached; reason says why.
	ConnectionStateOffline ConnectionState = "OFFLINE"
	// FRM answered but has a save loaded other than the one this session is pinned to.
	ConnectionStateSaveMismatch ConnectionState = "SAVE_MISMATCH"
)

var AllConnectionState = []ConnectionState{
	ConnectionStateConnecting,
	ConnectionStateOnline,
	ConnectionStateOffline,
	ConnectionStateSaveMismatch,
}

func (e ConnectionState) IsValid() bool {
	switch e {
	case ConnectionStateConnecting, ConnectionStateOnline, ConnectionStateOffline, ConnectionStateSaveMismatch:
		return true
	}
	return false
}

func (e ConnectionState) String() string {
	return string(e)
}

func (e *ConnectionState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectionState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectionState", str)
	}
	return nil
}

func (e ConnectionState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectionState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectionState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// ConnectivityReason explains why a session is unreachable, so the UI can say more
// than "offline".
type ConnectivityReason string

const (
	// The session is reachable.
	ConnectivityReasonNone ConnectivityReason = "NONE"
	// Nothing answered: timed out or refused. FRM is most likely not running.
	ConnectivityReasonNoResponse ConnectivityReason = "NO_RESPONSE"
	// Something answered but it was not FRM: an HTTP error, TLS failure, or a body that does not parse.
	ConnectivityReasonBadResponse ConnectivityReason = "BAD_RESPONSE"
)

var AllConnectivityReason = []ConnectivityReason{
	ConnectivityReasonNone,
	ConnectivityReasonNoResponse,
	ConnectivityReasonBadResponse,
}

func (e ConnectivityReason) IsValid() bool {
	switch e {
	case ConnectivityReasonNone, ConnectivityReasonNoResponse, ConnectivityReasonBadResponse:
		return true
	}
	return false
}

func (e ConnectivityReason) String() string {
	return string(e)
}

func (e *ConnectivityReason) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectivityReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectivityReason", str)
	}
	return nil
}

func (e ConnectivityReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectivityReason) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectivityReason) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DroneStatus string

const (
	DroneStatusIdle    DroneStatus = "IDLE"
	DroneStatusFlying  DroneStatus = "FLYING"
	DroneStatusDocking DroneStatus = "DOCKING"
)

var AllDroneStatus = []DroneStatus{
	DroneStatusIdle,
	DroneStatusFlying,
	DroneStatusDocking,
}

func (e DroneStatus) IsValid() bool {
	switch e {
	case DroneStatusIdle, DroneStatusFlying, DroneStatusDocking:
		return true
	}
	return false
}

func (e DroneStatus) String() string {
	return string(e)
}

func (e *DroneStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DroneStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DroneStatus", str)
	}
	return nil
}

func (e DroneStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DroneStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DroneStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ExplorerStatus string

const (
	ExplorerStatusSelfDriving   ExplorerStatus = "SELF_DRIVING"
	ExplorerStatusManualDriving ExplorerStatus = "MANUAL_DRIVING"
	ExplorerStatusParked        ExplorerStatus = "PARKED"
	ExplorerStatusUnknown       ExplorerStatus = "UNKNOWN"
)

var AllExplorerStatus = []ExplorerStatus{
	ExplorerStatusSelfDriving,
	ExplorerStatusManualDriving,
	ExplorerStatusParked,
	ExplorerStatusUnknown,
}

func (e ExplorerStatus) IsValid() bool {
	switch e {
	case ExplorerStatusSelfDriving, ExplorerStatusManualDriving, ExplorerStatusParked, ExplorerStatusUnknown:
		return true
	}
	return false
}

func (e ExplorerStatus) String() string {
	return string(e)
}

func (e *ExplorerStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExplorerStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExplorerStatus", str)
	}
	return nil
}

func (e ExplorerStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExplorerStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExplorerStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FaunaType string

const (
	FaunaTypeLizardDoggo      FaunaType = "LIZARD_DOGGO"
	FaunaTypeFluffyTailedHog  FaunaType = "FLUFFY_TAILED_HOG"
	FaunaTypeSpitter          FaunaType = "SPITTER"
	FaunaTypeStinger          FaunaType = "STINGER"
	FaunaTypeFlyingCrab       FaunaType = "FLYING_CRAB"
	FaunaTypeNonFlyingBird    FaunaType = "NON_FLYING_BIRD"
	FaunaTypeSpaceGiraffe     FaunaType = "SPACE_GIRAFFE"
	FaunaTypeSporeFlower      FaunaType = "SPORE_FLOWER"
	FaunaTypeLeafBug          FaunaType = "LEAF_BUG"
	FaunaTypeGrassSprite      FaunaType = "GRASS_SPRITE"
	FaunaTypeCaveBat          FaunaType = "CAVE_BAT"
	FaunaTypeGiantFlyingManta FaunaType = "GIANT_FLYING_MANTA"
	FaunaTypeLakeShark        FaunaType = "LAKE_SHARK"
	FaunaTypeWalker           FaunaType = "WALKER"
)

var AllFaunaType = []FaunaType{
	FaunaTypeLizardDoggo,
	FaunaTypeFluffyTailedHog,
	FaunaTypeSpitter,
	FaunaTypeStinger,
	FaunaTypeFlyingCrab,
	FaunaTypeNonFlyingBird,
	FaunaTypeSpaceGiraffe,
	FaunaTypeSporeFlower,
	FaunaTypeLeafBug,
	FaunaTypeGrassSprite,
	FaunaTypeCaveBat,
	FaunaTypeGiantFlyingManta,
	FaunaTypeLakeShark,
	FaunaTypeWalker,
}

func (e FaunaType) IsValid() bool {
	switch e {
	case FaunaTypeLizardDoggo, FaunaTypeFluffyTailedHog, FaunaTypeSpitter, FaunaTypeStinger, FaunaTypeFlyingCrab, FaunaTypeNonFlyingBird, FaunaTypeSpaceGiraffe, FaunaTypeSporeFlower, FaunaTypeLeafBug, FaunaTypeGrassSprite, FaunaTypeCaveBat, FaunaTypeGiantFlyingManta, FaunaTypeLakeShark, FaunaTypeWalker:
		return true
	}
	return false
}

func (e FaunaType) String() string {
	return string(e)
}

func (e *FaunaType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FaunaType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FaunaType", str)
	}
	return nil
}

func (e FaunaType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FaunaType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FaunaType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FloraType string

const (
	FloraTypeTree            FloraType = "TREE"
	FloraTypeLeaves          FloraType = "LEAVES"
	FloraTypeFlowerPetals    FloraType = "FLOWER_PETALS"
	FloraTypeBaconAgaric     FloraType = "BACON_AGARIC"
	FloraTypePaleberry       FloraType = "PALEBERRY"
	FloraTypeBerylNut        FloraType = "BERYL_NUT"
	FloraTypeMycelia         FloraType = "MYCELIA"
	FloraTypeVines           FloraType = "VINES"
	FloraTypeBlueCapMushroom FloraType = "BLUE_CAP_MUSHROOM"
	FloraTypePinkJellyfish   FloraType = "PINK_JELLYFISH"
)

var AllFloraType = []FloraType{
	FloraTypeTree,
	FloraTypeLeaves,
	FloraTypeFlowerPetals,
	FloraTypeBaconAgaric,
	FloraTypePaleberry,
	FloraTypeBerylNut,
	FloraTypeMycelia,
	FloraTypeVines,
	FloraTypeBlueCapMushroom,
	FloraTypePinkJellyfish,
}

func (e FloraType) IsValid() bool {
	switch e {
	case FloraTypeTree, FloraTypeLeaves, FloraTypeFlowerPetals, FloraTypeBaconAgaric, FloraTypePaleberry, FloraTypeBerylNut, FloraTypeMycelia, FloraTypeVines, FloraTypeBlueCapMushroom, FloraTypePinkJellyfish:
		return true
	}
	return false
}

func (e FloraType) String() string {
	return string(e)
}

func (e *FloraType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FloraType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FloraType", str)
	}
	return nil
}

func (e FloraType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FloraType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FloraType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type HistoryDataType string

const (
	HistoryDataTypeCircuits       HistoryDataType = "CIRCUITS"
	HistoryDataTypeFactoryStats   HistoryDataType = "FACTORY_STATS"
	HistoryDataTypeProdStats      HistoryDataType = "PROD_STATS"
	HistoryDataTypeGeneratorStats HistoryDataType = "GENERATOR_STATS"
	HistoryDataTypeSinkStats      HistoryDataType = "SINK_STATS"
)

var AllHistoryDataType = []HistoryDataType{
	HistoryDataTypeCircuits,
	HistoryDataTypeFactoryStats,
	HistoryDataTypeProdStats,
	HistoryDataTypeGeneratorStats,
	HistoryDataTypeSinkStats,
}

func (e HistoryDataType) IsValid() bool {
	switch e {
	case HistoryDataTypeCircuits, HistoryDataTypeFactoryStats, HistoryDataTypeProdStats, HistoryDataTypeGeneratorStats, HistoryDataTypeSinkStats:
		return true
	}
	return false
}

func (e HistoryDataType) String() string {
	return string(e)
}

func (e *HistoryDataType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HistoryDataType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HistoryDataType", str)
	}
	return nil
}

func (e HistoryDataType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HistoryDataType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HistoryDataType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LogLevel string

const (
	LogLevelTrace   LogLevel = "TRACE"
	LogLevelDebug   LogLevel = "DEBUG"
	LogLevelInfo    LogLevel = "INFO"
	LogLevelWarning LogLevel = "WARNING"
	LogLevelError   LogLevel = "ERROR"
)

var AllLogLevel = []LogLevel{
	LogLevelTrace,
	LogLevelDebug,
	LogLevelInfo,
	LogLevelWarning,
	LogLevelError,
}

func (e LogLevel) IsValid() bool {
	switch e {
	case LogLevelTrace, LogLevelDebug, LogLevelInfo, LogLevelWarning, LogLevelError:
		return true
	}
	return false
}

func (e LogLevel) String() string {
	return string(e)
}

func (e *LogLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LogLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LogLevel", str)
	}
	return nil
}

func (e LogLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LogLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LogLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MachineCategory string

const (
	MachineCategoryFactory   MachineCategory = "FACTORY"
	MachineCategoryExtractor MachineCategory = "EXTRACTOR"
	MachineCategoryGenerator MachineCategory = "GENERATOR"
)

var AllMachineCategory = []MachineCategory{
	MachineCategoryFactory,
	MachineCategoryExtractor,
	MachineCategoryGenerator,
}

func (e MachineCategory) IsValid() bool {
	switch e {
	case MachineCategoryFactory, MachineCategoryExtractor, MachineCategoryGenerator:
		return true
	}
	return false
}

func (e MachineCategory) String() string {
	return string(e)
}

func (e *MachineCategory) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MachineCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MachineCategory", str)
	}
	return nil
}

func (e MachineCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MachineCategory) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MachineCategory) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MachineStatus string

const (
	MachineStatusOperating    MachineStatus = "OPERATING"
	MachineStatusIdle         MachineStatus = "IDLE"
	MachineStatusPaused       MachineStatus = "PAUSED"
	MachineStatusUnconfigured MachineStatus = "UNCONFIGURED"
	MachineStatusUnknown      MachineStatus = "UNKNOWN"
)

var AllMachineStatus = []MachineStatus{
	MachineStatusOperating,
	MachineStatusIdle,
	MachineStatusPaused,
	MachineStatusUnconfigured,
	MachineStatusUnknown,
}

func (e MachineStatus) IsValid() bool {
	switch e {
	case MachineStatusOperating, MachineStatusIdle, MachineStatusPaused, MachineStatusUnconfigured, MachineStatusUnknown:
		return true
	}
	return false
}

func (e MachineStatus) String() string {
	return string(e)
}

func (e *MachineStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MachineStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MachineStatus", str)
	}
	return nil
}

func (e MachineStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MachineStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MachineStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MachineType string

const (
	MachineTypeAssembler           MachineType = "ASSEMBLER"
	MachineTypeConstructor         MachineType = "CONSTRUCTOR"
	MachineTypeFoundry             MachineType = "FOUNDRY"
	MachineTypeManufacturer        MachineType = "MANUFACTURER"
	MachineTypeRefinery            MachineType = "REFINERY"
	MachineTypeSmelter             MachineType = "SMELTER"
	MachineTypeBlender             MachineType = "BLENDER"
	MachineTypePackager            MachineType = "PACKAGER"
	MachineTypeParticleAccelerator MachineType = "PARTICLE_ACCELERATOR"
	MachineTypeMiner               MachineType = "MINER"
	MachineTypeOilExtractor        MachineType = "OIL_EXTRACTOR"
	MachineTypeWaterExtractor      MachineType = "WATER_EXTRACTOR"
	MachineTypeBiomassBurner       MachineType = "BIOMASS_BURNER"
	MachineTypeCoalGenerator       MachineType = "COAL_GENERATOR"
	MachineTypeFuelGenerator       MachineType = "FUEL_GENERATOR"
	MachineTypeGeothermalGenerator MachineType = "GEOTHERMAL_GENERATOR"
	MachineTypeNuclearPowerPlant   MachineType = "NUCLEAR_POWER_PLANT"
)

var AllMachineType = []MachineType{
	MachineTypeAssembler,
	MachineTypeConstructor,
	MachineTypeFoundry,
	MachineTypeManufacturer,
	MachineTypeRefinery,
	MachineTypeSmelter,
	MachineTypeBlender,
	MachineTypePackager,
	MachineTypeParticleAccelerator,
	MachineTypeMiner,
	MachineTypeOilExtractor,
	MachineTypeWaterExtractor,
	MachineTypeBiomassBurner,
	MachineTypeCoalGenerator,
	MachineTypeFuelGenerator,
	MachineTypeGeothermalGenerator,
	MachineTypeNuclearPowerPlant,
}

func (e MachineType) IsValid() bool {
	switch e {
	case MachineTypeAssembler, MachineTypeConstructor, MachineTypeFoundry, MachineTypeManufacturer, MachineTypeRefinery, MachineTypeSmelter, MachineTypeBlender, MachineTypePackager, MachineTypeParticleAccelerator, MachineTypeMiner, MachineTypeOilExtractor, MachineTypeWaterExtractor, MachineTypeBiomassBurner, MachineTypeCoalGenerator, MachineTypeFuelGenerator, MachineTypeGeothermalGenerator, MachineTypeNuclearPowerPlant:
		return true
	}
	return false
}

func (e MachineType) String() string {
	return string(e)
}

func (e *MachineType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MachineType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MachineType", str)
	}
	return nil
}

func (e MachineType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MachineType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MachineType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NodeType string

const (
	NodeTypeNode              NodeType = "NODE"
	NodeTypeGeyser            NodeType = "GEYSER"
	NodeTypeFrackingCore      NodeType = "FRACKING_CORE"
	NodeTypeFrackingSatellite NodeType = "FRACKING_SATELLITE"
)

var AllNodeType = []NodeType{
	NodeTypeNode,
	NodeTypeGeyser,
	NodeTypeFrackingCore,
	NodeTypeFrackingSatellite,
}

func (e NodeType) IsValid() bool {
	switch e {
	case NodeTypeNode, NodeTypeGeyser, NodeTypeFrackingCore, NodeTypeFrackingSatellite:
		return true
	}
	return false
}

func (e NodeType) String() string {
	return string(e)
}

func (e *NodeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NodeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NodeType", str)
	}
	return nil
}

func (e NodeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NodeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NodeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PowerType string

const (
	PowerTypeBiomass    PowerType = "BIOMASS"
	PowerTypeCoal       PowerType = "COAL"
	PowerTypeFuel       PowerType = "FUEL"
	PowerTypeGeothermal PowerType = "GEOTHERMAL"
	PowerTypeNuclear    PowerType = "NUCLEAR"
	PowerTypeUnknown    PowerType = "UNKNOWN"
)

var AllPowerType = []PowerType{
	PowerTypeBiomass,
	PowerTypeCoal,
	PowerTypeFuel,
	PowerTypeGeothermal,
	PowerTypeNuclear,
	PowerTypeUnknown,
}

func (e PowerType) IsValid() bool {
	switch e {
	case PowerTypeBiomass, PowerTypeCoal, PowerTypeFuel, PowerTypeGeothermal, PowerTypeNuclear, PowerTypeUnknown:
		return true
	}
	return false
}

func (e PowerType) String() string {
	return string(e)
}

func (e *PowerType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PowerType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PowerType", str)
	}
	return nil
}

func (e PowerType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PowerType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PowerType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ResourceNodePurity string

const (
	ResourceNodePurityImpure ResourceNodePurity = "IMPURE"
	ResourceNodePurityNormal ResourceNodePurity = "NORMAL"
	ResourceNodePurityPure   ResourceNodePurity = "PURE"
)

var AllResourceNodePurity = []ResourceNodePurity{
	ResourceNodePurityImpure,
	ResourceNodePurityNormal,
	ResourceNodePurityPure,
}

func (e ResourceNodePurity) IsValid() bool {
	switch e {
	case ResourceNodePurityImpure, ResourceNodePurityNormal, ResourceNodePurityPure:
		return true
	}
	return false
}

func (e ResourceNodePurity) String() string {
	return string(e)
}

func (e *ResourceNodePurity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ResourceNodePurity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ResourceNodePurity", str)
	}
	return nil
}

func (e ResourceNodePurity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ResourceNodePurity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ResourceNodePurity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ResourceType string

const (
	ResourceTypeIronOre     ResourceType = "IRON_ORE"
	ResourceTypeCopperOre   ResourceType = "COPPER_ORE"
	ResourceTypeLimestone   ResourceType = "LIMESTONE"
	ResourceTypeCoal        ResourceType = "COAL"
	ResourceTypeSam         ResourceType = "SAM"
	ResourceTypeSulfur      ResourceType = "SULFUR"
	ResourceTypeCateriumOre ResourceType = "CATERIUM_ORE"
	ResourceTypeBauxite     ResourceType = "BAUXITE"
	ResourceTypeRawQuartz   ResourceType = "RAW_QUARTZ"
	ResourceTypeUranium     ResourceType = "URANIUM"
	ResourceTypeCrudeOil    ResourceType = "CRUDE_OIL"
	ResourceTypeGeyser      ResourceType = "GEYSER"
	ResourceTypeNitrogenGas ResourceType = "NITROGEN_GAS"
)

var AllResourceType = []ResourceType{
	ResourceTypeIronOre,
	ResourceTypeCopperOre,
	ResourceTypeLimestone,
	ResourceTypeCoal,
	ResourceTypeSam,
	ResourceTypeSulfur,
	ResourceTypeCateriumOre,
	ResourceTypeBauxite,
	ResourceTypeRawQuartz,
	ResourceTypeUranium,
	ResourceTypeCrudeOil,
	ResourceTypeGeyser,
	ResourceTypeNitrogenGas,
}

func (e ResourceType) IsValid() bool {
	switch e {
	case ResourceTypeIronOre, ResourceTypeCopperOre, ResourceTypeLimestone, ResourceTypeCoal, ResourceTypeSam, ResourceTypeSulfur, ResourceTypeCateriumOre, ResourceTypeBauxite, ResourceTypeRawQuartz, ResourceTypeUranium, ResourceTypeCrudeOil, ResourceTypeGeyser, ResourceTypeNitrogenGas:
		return true
	}
	return false
}

func (e ResourceType) String() string {
	return string(e)
}

func (e *ResourceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ResourceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ResourceType", str)
	}
	return nil
}

func (e ResourceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ResourceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ResourceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionStage string

const (
	SessionStageInit  SessionStage = "INIT"
	SessionStageReady SessionStage = "READY"
)

var AllSessionStage = []SessionStage{
	SessionStageInit,
	SessionStageReady,
}

func (e SessionStage) IsValid() bool {
	switch e {
	case SessionStageInit, SessionStageReady:
		return true
	}
	return false
}

func (e SessionStage) String() string {
	return string(e)
}

func (e *SessionStage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionStage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionStage", str)
	}
	return nil
}

func (e SessionStage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionStage) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionStage) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SignalType string

const (
	SignalTypeSomersloop      SignalType = "SOMERSLOOP"
	SignalTypeMercerSphere    SignalType = "MERCER_SPHERE"
	SignalTypeBluePowerSlug   SignalType = "BLUE_POWER_SLUG"
	SignalTypeYellowPowerSlug SignalType = "YELLOW_POWER_SLUG"
	SignalTypePurplePowerSlug SignalType = "PURPLE_POWER_SLUG"
	SignalTypeHardDrive       SignalType = "HARD_DRIVE"
)

var AllSignalType = []SignalType{
	SignalTypeSomersloop,
	SignalTypeMercerSphere,
	SignalTypeBluePowerSlug,
	SignalTypeYellowPowerSlug,
	SignalTypePurplePowerSlug,
	SignalTypeHardDrive,
}

func (e SignalType) IsValid() bool {
	switch e {
	case SignalTypeSomersloop, SignalTypeMercerSphere, SignalTypeBluePowerSlug, SignalTypeYellowPowerSlug, SignalTypePurplePowerSlug, SignalTypeHardDrive:
		return true
	}
	return false
}

func (e SignalType) String() string {
	return string(e)
}

func (e *SignalType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SignalType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SignalType", str)
	}
	return nil
}

func (e SignalType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SignalType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SignalType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SplitterMergerType string

const (
	SplitterMergerTypeConveyorMerger       SplitterMergerType = "CONVEYOR_MERGER"
	SplitterMergerTypeConveyorSplitter     SplitterMergerType = "CONVEYOR_SPLITTER"
	SplitterMergerTypeProgrammableSplitter SplitterMergerType = "PROGRAMMABLE_SPLITTER"
	SplitterMergerTypeSmartSplitter        SplitterMergerType = "SMART_SPLITTER"
)

var AllSplitterMergerType = []SplitterMergerType{
	SplitterMergerTypeConveyorMerger,
	SplitterMergerTypeConveyorSplitter,
	SplitterMergerTypeProgrammableSplitter,
	SplitterMergerTypeSmartSplitter,
}

func (e SplitterMergerType) IsValid() bool {
	switch e {
	case SplitterMergerTypeConveyorMerger, SplitterMergerTypeConveyorSplitter, SplitterMergerTypeProgrammableSplitter, SplitterMergerTypeSmartSplitter:
		return true
	}
	return false
}

func (e SplitterMergerType) String() string {
	return string(e)
}

func (e *SplitterMergerType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SplitterMergerType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SplitterMergerType", str)
	}
	return nil
}

func (e SplitterMergerType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SplitterMergerType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SplitterMergerType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StorageType string

const (
	StorageTypeBlueprintStorageBox        StorageType = "BLUEPRINT_STORAGE_BOX"
	StorageTypeDimensionalDepotUploader   StorageType = "DIMENSIONAL_DEPOT_UPLOADER"
	StorageTypeIndustrialStorageContainer StorageType = "INDUSTRIAL_STORAGE_CONTAINER"
	StorageTypePersonalStorageBox         StorageType = "PERSONAL_STORAGE_BOX"
	StorageTypeStorageContainer           StorageType = "STORAGE_CONTAINER"
)

var AllStorageType = []StorageType{
	StorageTypeBlueprintStorageBox,
	StorageTypeDimensionalDepotUploader,
	StorageTypeIndustrialStorageContainer,
	StorageTypePersonalStorageBox,
	StorageTypeStorageContainer,
}

func (e StorageType) IsValid() bool {
	switch e {
	case StorageTypeBlueprintStorageBox, StorageTypeDimensionalDepotUploader, StorageTypeIndustrialStorageContainer, StorageTypePersonalStorageBox, StorageTypeStorageContainer:
		return true
	}
	return false
}

func (e StorageType) String() string {
	return string(e)
}

func (e *StorageType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StorageType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StorageType", str)
	}
	return nil
}

func (e StorageType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StorageType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StorageType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TractorStatus string

const (
	TractorStatusSelfDriving   TractorStatus = "SELF_DRIVING"
	TractorStatusManualDriving TractorStatus = "MANUAL_DRIVING"
	TractorStatusParked        TractorStatus = "PARKED"
	TractorStatusUnknown       TractorStatus = "UNKNOWN"
)

var AllTractorStatus = []TractorStatus{
	TractorStatusSelfDriving,
	TractorStatusManualDriving,
	TractorStatusParked,
	TractorStatusUnknown,
}

func (e TractorStatus) IsValid() bool {
	switch e {
	case TractorStatusSelfDriving, TractorStatusManualDriving, TractorStatusParked, TractorStatusUnknown:
		return true
	}
	return false
}

func (e TractorStatus) String() string {
	return string(e)
}

func (e *TractorStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TractorStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TractorStatus", str)
	}
	return nil
}

func (e TractorStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TractorStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TractorStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TrainRailType string

const (
	TrainRailTypeRailway TrainRailType = "RAILWAY"
)

var AllTrainRailType = []TrainRailType{
	TrainRailTypeRailway,
}

func (e TrainRailType) IsValid() bool {
	switch e {
	case TrainRailTypeRailway:
		return true
	}
	return false
}

func (e TrainRailType) String() string {
	return string(e)
}

func (e *TrainRailType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TrainRailType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TrainRailType", str)
	}
	return nil
}

func (e TrainRailType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TrainRailType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TrainRailType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TrainStationPlatformMode string

const (
	TrainStationPlatformModeImport TrainStationPlatformMode = "IMPORT"
	TrainStationPlatformModeExport TrainStationPlatformMode = "EXPORT"
)

var AllTrainStationPlatformMode = []TrainStationPlatformMode{
	TrainStationPlatformModeImport,
	TrainStationPlatformModeExport,
}

func (e TrainStationPlatformMode) IsValid() bool {
	switch e {
	case TrainStationPlatformModeImport, TrainStationPlatformModeExport:
		return true
	}
	return false
}

func (e TrainStationPlatformMode) String() string {
	return string(e)
}

func (e *TrainStationPlatformMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TrainStationPlatformMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TrainStationPlatformMode", str)
	}
	return nil
}

func (e TrainStationPlatformMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TrainStationPlatformMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TrainStationPlatformMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TrainStationPlatformStatus string

const (
	TrainStationPlatformStatusIdle    TrainStationPlatformStatus = "IDLE"
	TrainStationPlatformStatusDocking TrainStationPlatformStatus = "DOCKING"
)

var AllTrainStationPlatformStatus = []TrainStationPlatformStatus{
	TrainStationPlatformStatusIdle,
	TrainStationPlatformStatusDocking,
}

func (e TrainStationPlatformStatus) IsValid() bool {
	switch e {
	case TrainStationPlatformStatusIdle, TrainStationPlatformStatusDocking:
		return true
	}
	return false
}

func (e TrainStationPlatformStatus) String() string {
	return string(e)
}

func (e *TrainStationPlatformStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TrainStationPlatformStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TrainStationPlatformStatus", str)
	}
	return nil
}

func (e TrainStationPlatformStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TrainStationPlatformStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TrainStationPlatformStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TrainStationPlatformType string

const (
	TrainStationPlatformTypeFreight      TrainStationPlatformType = "FREIGHT"
	TrainStationPlatformTypeFluidFreight TrainStationPlatformType = "FLUID_FREIGHT"
)

var AllTrainStationPlatformType = []TrainStationPlatformType{
	TrainStationPlatformTypeFreight,
	TrainStationPlatformTypeFluidFreight,
}

func (e TrainStationPlatformType) IsValid() bool {
	switch e {
	case TrainStationPlatformTypeFreight, TrainStationPlatformTypeFluidFreight:
		return true
	}
	return false
}

func (e TrainStationPlatformType) String() string {
	return string(e)
}

func (e *TrainStationPlatformType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TrainStationPlatformType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TrainStationPlatformType", str)
	}
	return nil
}

func (e TrainStationPlatformType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TrainStationPlatformType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TrainStationPlatformType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TrainStatus string

const (
	TrainStatusSelfDriving   TrainStatus = "SELF_DRIVING"
	TrainStatusManualDriving TrainStatus = "MANUAL_DRIVING"
	TrainStatusParked        TrainStatus = "PARKED"
	TrainStatusDocking       TrainStatus = "DOCKING"
	TrainStatusDerailed      TrainStatus = "DERAILED"
	TrainStatusUnknown       TrainStatus = "UNKNOWN"
)

var AllTrainStatus = []TrainStatus{
	TrainStatusSelfDriving,
	TrainStatusManualDriving,
	TrainStatusParked,
	TrainStatusDocking,
	TrainStatusDerailed,
	TrainStatusUnknown,
}

func (e TrainStatus) IsValid() bool {
	switch e {
	case TrainStatusSelfDriving, TrainStatusManualDriving, TrainStatusParked, TrainStatusDocking, TrainStatusDerailed, TrainStatusUnknown:
		return true
	}
	return false
}

func (e TrainStatus) String() string {
	return string(e)
}

func (e *TrainStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TrainStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TrainStatus", str)
	}
	return nil
}

func (e TrainStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TrainStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TrainStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TrainType string

const (
	TrainTypeFreight    TrainType = "FREIGHT"
	TrainTypeLocomotive TrainType = "LOCOMOTIVE"
)

var AllTrainType = []TrainType{
	TrainTypeFreight,
	TrainTypeLocomotive,
}

func (e TrainType) IsValid() bool {
	switch e {
	case TrainTypeFreight, TrainTypeLocomotive:
		return true
	}
	return false
}

func (e TrainType) String() string {
	return string(e)
}

func (e *TrainType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TrainType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TrainType", str)
	}
	return nil
}

func (e TrainType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TrainType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TrainType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TruckStatus string

const (
	TruckStatusSelfDriving   TruckStatus = "SELF_DRIVING"
	TruckStatusManualDriving TruckStatus = "MANUAL_DRIVING"
	TruckStatusParked        TruckStatus = "PARKED"
	TruckStatusUnknown       TruckStatus = "UNKNOWN"
)

var AllTruckStatus = []TruckStatus{
	TruckStatusSelfDriving,
	TruckStatusManualDriving,
	TruckStatusParked,
	TruckStatusUnknown,
}

func (e TruckStatus) IsValid() bool {
	switch e {
	case TruckStatusSelfDriving, TruckStatusManualDriving, TruckStatusParked, TruckStatusUnknown:
		return true
	}
	return false
}

func (e TruckStatus) String() string {
	return string(e)
}

func (e *TruckStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TruckStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TruckStatus", str)
	}
	return nil
}

func (e TruckStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TruckStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TruckStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VehiclePathType string

const (
	VehiclePathTypeExplorer    VehiclePathType = "EXPLORER"
	VehiclePathTypeFactoryCart VehiclePathType = "FACTORY_CART"
	VehiclePathTypeTruck       VehiclePathType = "TRUCK"
	VehiclePathTypeTractor     VehiclePathType = "TRACTOR"
)

var AllVehiclePathType = []VehiclePathType{
	VehiclePathTypeExplorer,
	VehiclePathTypeFactoryCart,
	VehiclePathTypeTruck,
	VehiclePathTypeTractor,
}

func (e VehiclePathType) IsValid() bool {
	switch e {
	case VehiclePathTypeExplorer, VehiclePathTypeFactoryCart, VehiclePathTypeTruck, VehiclePathTypeTractor:
		return true
	}
	return false
}

func (e VehiclePathType) String() string {
	return string(e)
}

func (e *VehiclePathType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VehiclePathType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VehiclePathType", str)
	}
	return nil
}

func (e VehiclePathType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VehiclePathType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VehiclePathType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
